Add TypeUtteranceEndResponse & handle case in live.router
deepgram/deepgram-go-sdk pull request #147
Opened 2023-12-18 21:23 UTC by boyswan

## Proposed changes

Reference: https://github.com/deepgram/deepgram-go-sdk/issues/146

## Types of changes

What types of changes does your code introduce to the community Go SDK?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update or tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](../CONTRIBUTING.md) doc
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

2023-12-19 15:51 UTC, dvonthenen requested changes

2023-12-19 15:51 UTC, dvonthenen commented on pkg/api/live/v1/router.go
> +		return r.UtteranceEndResponse(byMsg)
Is appears that there is some byte stream that is returned from the Deepgram platform here. Can this be turned into a Go Struct?

2023-12-19 16:03 UTC, boyswan commented on pkg/api/live/v1/interfaces/interfaces.go
> +	UtteranceEnd() error
So this is something I wanted to discuss. There is actually no data in the byMsg, as the UtteranceEnd message contains nothing but `{ type: "UtteranceEnd" }`. Arguably I shouldn't be passing in byMsg at all - however I was wondering if you would prefer to have a `UtteranceEndReponse` empty struct for consistency?

2023-12-19 21:25 UTC, dvonthenen commented on pkg/api/live/v1/interfaces/interfaces.go
> +	UtteranceEnd() error
Yea, I think for compatibility sake, we probably want a structure even if it's empty.

The idea is that additional information could be passed back at some point and we can forward that onto the user. That change would be non-breaking and therefore it's better to have an empty structure than nothing at all. Users currently implementing where no information is passed back. Isn't looking at values in the structure anyways.

2023-12-20 23:11 UTC, dvonthenen commented
Thanks for the update. I'll take a look at this in a little bit! I super appreciate it!

2023-12-21 14:08 UTC, dvonthenen approved these changes

2023-12-21 14:08 UTC, merged